version: 2
jobs:
  build:
    working_directory: ~/circleci-fake-data
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get update
            sudo apt-get install libglpk-dev
            python -m venv env
            source env/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install .
            pytest -vv
