version: 2
jobs:
  build:
    working_directory: ~/circleci-fake-data
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: 
          command: | 
            sudo pip install -r requirements.txt
  test:
    working_directory: ~/circleci-fake-data
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            pytest -vv
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test