version: 2
jobs:
  build:
    working_directory: ~/circleci-fake-data
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: 
          command: | 
            sudo apt get libglpk-dev            
            sudo pip install -r requirements.txt
      - run:
          command: |
            pytest -vv
